INSERT INTO users (id, name, age) VALUES (1, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (2, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (3, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (4, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (5, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (6, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (7, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (8, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (9, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (10, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (11, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (12, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (13, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (14, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (15, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (16, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (17, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (18, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (19, 'Bob', 76);
INSERT INTO users (id, name, age) VALUES (20, 'Bob', 76);

INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, 'Title', 'cats', 350, "9/12/17", "2/17/18");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, 'Title', 'cats', 350, "9/12/17", "2/17/18");

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, 500, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, 500, 1, 1);
